buildah floating tags

diff --git a/task/buildah/0.1/buildah.yaml b/task/buildah/0.1/buildah.yaml
--- a/task/buildah/0.1/buildah.yaml
+++ b/task/buildah/0.1/buildah.yaml
@@ -54,6 +54,10 @@ spec:
     description: The image is built from this commit.
     type: string
     default: ""
+  - name: TAGS
+    description: Additional floating tags for the image.
+    type: string
+    default: ""
   results:
   - description: Digest of the image just built
     name: IMAGE_DIGEST
@@ -86,6 +90,8 @@ spec:
       value: $(params.TLSVERIFY)
     - name: IMAGE_EXPIRES_AFTER
       value: $(params.IMAGE_EXPIRES_AFTER)
+    - name: TAGS
+      value: $(params.TAGS)
   steps:
   - image: $(params.BUILDER_IMAGE)
     name: build
@@ -307,6 +313,24 @@ spec:
           echo "Failed to push sbom image to registry after ${max_run} tries"
           exit 1
       fi
+      for tag in $TAGS; do
+        newImage="$(echo $IMAGE | cut -d: -f1):$tag"
+        buildah tag $IMAGE $newImage
+        
+        for run in $(seq 1 $max_run); do
+          status=0
+          [ "$run" -gt 1 ] && sleep $sleep_sec
+          echo "Pushing tag $newImage to registry"
+          buildah push \
+            --tls-verify=$TLSVERIFY \
+            --digestfile $(workspaces.source.path)/image-digest $newImage \
+            docker://$newImage && break || status=$?
+        done
+        if [ "$status" -ne 0 ]; then
+            echo "Failed to push sbom image to registry after ${max_run} tries"
+            exit 1
+        fi
+      done
 
       cat "$(workspaces.source.path)"/image-digest | tee $(results.IMAGE_DIGEST.path)
       echo -n "$IMAGE" | tee $(results.IMAGE_URL.path)
